Remove docs requirement in circle for now

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -642,15 +642,16 @@ jobs:
       - run:
           name: Run Tests
           command: yarn --cwd=packages/sdk/contractkit test
-      - run:
-          name: Fail if someone forgot to commit contractkit docs
-          command: |
-            yarn --cwd=packages/sdk/contractkit docs
-            if [[ $(git status packages/docs/developer-resources/contractkit --porcelain) ]]; then
-              git --no-pager diff packages/docs/developer-resources/contractkit
-              echo "There are git differences after generating contractkit docs"
-              exit 1
-            fi
+      # TODO: remove comment after new docs generation
+      # - run:
+      #     name: Fail if someone forgot to commit contractkit docs
+      #     command: |
+      #       yarn --cwd=packages/sdk/contractkit docs
+      #       if [[ $(git status packages/docs/developer-resources/contractkit --porcelain) ]]; then
+      #         git --no-pager diff packages/docs/developer-resources/contractkit
+      #         echo "There are git differences after generating contractkit docs"
+      #         exit 1
+      #       fi
       - persist_to_workspace:
           root: .
           paths:
