reenable all ci test

diff --git a/.github/workflows/celo-monorepo.yml b/.github/workflows/celo-monorepo.yml
--- a/.github/workflows/celo-monorepo.yml
+++ b/.github/workflows/celo-monorepo.yml
@@ -160,93 +160,93 @@ jobs:
       - run: yarn run prettify:diff
       - run: yarn run lint
 
-  # protocol-test-release:
-  #   name: Protocol Test Release
-  #   runs-on: ['self-hosted', 'monorepo-node18']
-  #   timeout-minutes: 500
-  #   needs: [install-dependencies, lint-checks]
-  #   if: |
-  #     github.base_ref == 'master' || contains(github.base_ref, 'release') || contains(github.base_ref, 'production') ||
-  #     contains(needs.install-dependencies.outputs.all_modified_files, 'packages/protocol') ||
-  #     contains(needs.install-dependencies.outputs.all_modified_files, ',package.json') ||
-  #     contains(needs.install-dependencies.outputs.all_modified_files, ',yarn.lock') ||
-  #     false
-  #   steps:
-  #     - uses: actions/checkout@v4
-  #       with:
-  #         fetch-depth: 0
-  #         submodules: recursive
-  #     - name: Sync workspace
-  #       uses: ./.github/actions/sync-workspace
-  #       with:
-  #         artifacts_to_cache: ${{ needs.install-dependencies.outputs.artifacts_to_cache }}
-  #     - name: Download protocol devchain artifact
-  #       uses: dawidd6/action-download-artifact@v3
-  #       with:
-  #         workflow: protocol-devchain.yml
-  #         name: devchain-${{ env.RELEASE_TAG }}
-  #         path: packages/protocol/.tmp/devchain
-  #     - name: Copy DevChain and Build generated from released tag
-  #       run: |
-  #         BUILD_AND_DEVCHAIN_DIR=$(echo build/$(echo $RELEASE_TAG | sed -e 's/\//_/g'))
-  #         (cp -r packages/protocol/.tmp/devchain packages/protocol/$BUILD_AND_DEVCHAIN_DIR)
-  #     - name: Test against current release
-  #       run: |
-  #         echo "Comparing against $RELEASE_TAG"
-  #         BUILD_AND_DEVCHAIN_DIR=$(echo build/$(echo $RELEASE_TAG | sed -e 's/\//_/g'))
-  #         yarn --cwd packages/protocol ci:test-make-release -b $RELEASE_TAG -d $BUILD_AND_DEVCHAIN_DIR
+  protocol-test-release:
+    name: Protocol Test Release
+    runs-on: ['self-hosted', 'monorepo-node18']
+    timeout-minutes: 500
+    needs: [install-dependencies, lint-checks]
+    if: |
+      github.base_ref == 'master' || contains(github.base_ref, 'release') || contains(github.base_ref, 'production') ||
+      contains(needs.install-dependencies.outputs.all_modified_files, 'packages/protocol') ||
+      contains(needs.install-dependencies.outputs.all_modified_files, ',package.json') ||
+      contains(needs.install-dependencies.outputs.all_modified_files, ',yarn.lock') ||
+      false
+    steps:
+      - uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+          submodules: recursive
+      - name: Sync workspace
+        uses: ./.github/actions/sync-workspace
+        with:
+          artifacts_to_cache: ${{ needs.install-dependencies.outputs.artifacts_to_cache }}
+      - name: Download protocol devchain artifact
+        uses: dawidd6/action-download-artifact@v3
+        with:
+          workflow: protocol-devchain.yml
+          name: devchain-${{ env.RELEASE_TAG }}
+          path: packages/protocol/.tmp/devchain
+      - name: Copy DevChain and Build generated from released tag
+        run: |
+          BUILD_AND_DEVCHAIN_DIR=$(echo build/$(echo $RELEASE_TAG | sed -e 's/\//_/g'))
+          (cp -r packages/protocol/.tmp/devchain packages/protocol/$BUILD_AND_DEVCHAIN_DIR)
+      - name: Test against current release
+        run: |
+          echo "Comparing against $RELEASE_TAG"
+          BUILD_AND_DEVCHAIN_DIR=$(echo build/$(echo $RELEASE_TAG | sed -e 's/\//_/g'))
+          yarn --cwd packages/protocol ci:test-make-release -b $RELEASE_TAG -d $BUILD_AND_DEVCHAIN_DIR
 
-  # protocol-test-matrix:
-  #   # Keeping name short because GitHub UI does not handle long names well
-  #   name: ${{ matrix.name }}
-  #   runs-on: ['self-hosted', 'monorepo-node18']
-  #   timeout-minutes: 60
-  #   needs: [install-dependencies, lint-checks]
-  #   if: |
-  #     github.base_ref == 'master' || contains(github.base_ref, 'release') || contains(github.base_ref, 'staging') || contains(github.base_ref, 'production') ||
-  #     contains(needs.install-dependencies.outputs.all_modified_files, 'packages/protocol') ||
-  #     contains(needs.install-dependencies.outputs.all_modified_files, 'packages/typescript') ||
-  #     contains(needs.install-dependencies.outputs.all_modified_files, ',package.json') ||
-  #     contains(needs.install-dependencies.outputs.all_modified_files, ',yarn.lock') ||
-  #     false
-  #   strategy:
-  #     fail-fast: false
-  #     matrix:
-  #       include:
-  #         - name: Protocol Release Snapshots
-  #           command: |
-  #             yarn --cwd packages/protocol test:release-snapshots
-  #             if [[ $(git status packages/protocol/releaseData/versionReports --porcelain) ]]; then
-  #               git --no-pager diff packages/protocol/releaseData/versionReports
-  #               echo "There are git differences after generating release version report snapshots"
-  #               echo "If these changes are intended, update the 'releaseData/versionReports' accordingly"
-  #               exit 1
-  #             fi
-  #         - name: Protocol Common tests
-  #           command: |
-  #             yarn --cwd packages/protocol test common/
-  #         - name: Protocol Compatibility
-  #           command: |
-  #             yarn --cwd packages/protocol test compatibility/
-  #         - name: Protocol scripts test
-  #           command: |
-  #             yarn --cwd packages/protocol test:scripts
-  #   steps:
-  #     - uses: actions/checkout@v4
-  #       with:
-  #         submodules: recursive
-  #     - name: Sync workspace
-  #       uses: ./.github/actions/sync-workspace
-  #       with:
-  #         rebuild-package: 'true'
-  #         artifacts_to_cache: ${{ needs.install-dependencies.outputs.artifacts_to_cache }}
-  #     - name: Execute matrix command for test
-  #       uses: nick-fields/retry@v3
-  #       with:
-  #         timeout_minutes: 40
-  #         max_attempts: 3
-  #         command: |
-  #           ${{ matrix.command }}
+  protocol-test-matrix:
+    # Keeping name short because GitHub UI does not handle long names well
+    name: ${{ matrix.name }}
+    runs-on: ['self-hosted', 'monorepo-node18']
+    timeout-minutes: 60
+    needs: [install-dependencies, lint-checks]
+    if: |
+      github.base_ref == 'master' || contains(github.base_ref, 'release') || contains(github.base_ref, 'staging') || contains(github.base_ref, 'production') ||
+      contains(needs.install-dependencies.outputs.all_modified_files, 'packages/protocol') ||
+      contains(needs.install-dependencies.outputs.all_modified_files, 'packages/typescript') ||
+      contains(needs.install-dependencies.outputs.all_modified_files, ',package.json') ||
+      contains(needs.install-dependencies.outputs.all_modified_files, ',yarn.lock') ||
+      false
+    strategy:
+      fail-fast: false
+      matrix:
+        include:
+          - name: Protocol Release Snapshots
+            command: |
+              yarn --cwd packages/protocol test:release-snapshots
+              if [[ $(git status packages/protocol/releaseData/versionReports --porcelain) ]]; then
+                git --no-pager diff packages/protocol/releaseData/versionReports
+                echo "There are git differences after generating release version report snapshots"
+                echo "If these changes are intended, update the 'releaseData/versionReports' accordingly"
+                exit 1
+              fi
+          - name: Protocol Common tests
+            command: |
+              yarn --cwd packages/protocol test common/
+          - name: Protocol Compatibility
+            command: |
+              yarn --cwd packages/protocol test compatibility/
+          - name: Protocol scripts test
+            command: |
+              yarn --cwd packages/protocol test:scripts
+    steps:
+      - uses: actions/checkout@v4
+        with:
+          submodules: recursive
+      - name: Sync workspace
+        uses: ./.github/actions/sync-workspace
+        with:
+          rebuild-package: 'true'
+          artifacts_to_cache: ${{ needs.install-dependencies.outputs.artifacts_to_cache }}
+      - name: Execute matrix command for test
+        uses: nick-fields/retry@v3
+        with:
+          timeout_minutes: 40
+          max_attempts: 3
+          command: |
+            ${{ matrix.command }}
 
   end-to-end-geth-matrix:
     # Keeping name short because GitHub UI does not handle long names well
@@ -266,57 +266,57 @@ jobs:
       fail-fast: false
       matrix:
         include:
-          # - name: Transfer test
-          #   command: |
-          #     set -e
-          #     # Forcing to load go and rust paths
-          #     export PATH="/usr/local/go/bin:$HOME/.cargo/bin:${PATH}"
-          #     cd packages/celotool
-          #     ./ci_test_transfers.sh checkout ${CELO_BLOCKCHAIN_BRANCH_TO_TEST}
-          # - name: Blockchain Parameters test
-          #   command: |
-          #     set -e
-          #     export PATH="/usr/local/go/bin:$HOME/.cargo/bin:${PATH}"
-          #     cd packages/celotool
-          #     ./ci_test_blockchain_parameters.sh checkout ${CELO_BLOCKCHAIN_BRANCH_TO_TEST}
-          # - name: Slashing test
-            # command: |
-            #   set -e
-            #   export PATH="/usr/local/go/bin:$HOME/.cargo/bin:${PATH}"
-            #   cd packages/celotool
-            #   ./ci_test_slashing.sh checkout ${CELO_BLOCKCHAIN_BRANCH_TO_TEST}
+          - name: Transfer test
+            command: |
+              set -e
+              # Forcing to load go and rust paths
+              export PATH="/usr/local/go/bin:$HOME/.cargo/bin:${PATH}"
+              cd packages/celotool
+              ./ci_test_transfers.sh checkout ${CELO_BLOCKCHAIN_BRANCH_TO_TEST}
+          - name: Blockchain Parameters test
+            command: |
+              set -e
+              export PATH="/usr/local/go/bin:$HOME/.cargo/bin:${PATH}"
+              cd packages/celotool
+              ./ci_test_blockchain_parameters.sh checkout ${CELO_BLOCKCHAIN_BRANCH_TO_TEST}
+          - name: Slashing test
+            command: |
+              set -e
+              export PATH="/usr/local/go/bin:$HOME/.cargo/bin:${PATH}"
+              cd packages/celotool
+              ./ci_test_slashing.sh checkout ${CELO_BLOCKCHAIN_BRANCH_TO_TEST}
           - name: Governance test
             command: |
               set -e
               export PATH="/usr/local/go/bin:$HOME/.cargo/bin:${PATH}"
               cd packages/celotool
               ./ci_test_governance.sh checkout ${CELO_BLOCKCHAIN_BRANCH_TO_TEST}
-          # - name: Replica test
-          #   command: |
-          #     set -e
-          #     export PATH="/usr/local/go/bin:$HOME/.cargo/bin:${PATH}"
-          #     cd packages/celotool
-          #     ./ci_test_replicas.sh checkout ${CELO_BLOCKCHAIN_BRANCH_TO_TEST}
-          # - name: Sync test
-          #   command: |
-          #     set -e
-          #     export PATH="/usr/local/go/bin:$HOME/.cargo/bin:${PATH}"
-          #     cd packages/celotool
-          #     ./ci_test_sync.sh checkout ${CELO_BLOCKCHAIN_BRANCH_TO_TEST}
-          # - name: CIP35 eth compatibility test
-          #   command: |
-          #     set -e
-          #     export PATH="/usr/local/go/bin:$HOME/.cargo/bin:${PATH}"
-          #     cd packages/celotool
-          #     echo "Test is skipped because migrations somehow fail"
-          #     # ./ci_test_cip35.sh checkout ${CELO_BLOCKCHAIN_BRANCH_TO_TEST}
-          # - name: Validator order test
-            # command: |
-            #   set -e
-            #   export PATH="/usr/local/go/bin:$HOME/.cargo/bin:${PATH}"
-            #   cd packages/celotool
+          - name: Replica test
+            command: |
+              set -e
+              export PATH="/usr/local/go/bin:$HOME/.cargo/bin:${PATH}"
+              cd packages/celotool
+              ./ci_test_replicas.sh checkout ${CELO_BLOCKCHAIN_BRANCH_TO_TEST}
+          - name: Sync test
+            command: |
+              set -e
+              export PATH="/usr/local/go/bin:$HOME/.cargo/bin:${PATH}"
+              cd packages/celotool
+              ./ci_test_sync.sh checkout ${CELO_BLOCKCHAIN_BRANCH_TO_TEST}
+          - name: CIP35 eth compatibility test
+            command: |
+              set -e
+              export PATH="/usr/local/go/bin:$HOME/.cargo/bin:${PATH}"
+              cd packages/celotool
+              echo "Test is skipped because migrations somehow fail"
+              # ./ci_test_cip35.sh checkout ${CELO_BLOCKCHAIN_BRANCH_TO_TEST}
+          - name: Validator order test
+            command: |
+              set -e
+              export PATH="/usr/local/go/bin:$HOME/.cargo/bin:${PATH}"
+              cd packages/celotool
 
-            #   ./ci_test_validator_order.sh checkout ${CELO_BLOCKCHAIN_BRANCH_TO_TEST}
+              ./ci_test_validator_order.sh checkout ${CELO_BLOCKCHAIN_BRANCH_TO_TEST}
     steps:
       - uses: actions/checkout@v4
         with:
